export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_ID = "GET_BRANDS_ID";
export const GET_BRANDS_BY_NAME = "GET_BRANDS_BY_NAME";
export const GET_BRANDS_BY_QUERY = "GET_BRANDS_BY_QUERY";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_ID = "GET_PRODUCTS_ID";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const GET_PRODUCTS_BY_QUERY = "GET_PRODUCTS_BY_QUERY";